export const Books = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    year: 1925,
    description:
      "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set in the Jazz Age.",
    rating: 4.5,
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
    year: 1960,
    description:
      "A young girl in the racially charged Deep South learns about empathy and justice.",
    rating: 4.8,
    image: "https://covers.openlibrary.org/b/id/8225265-L.jpg",
  },
  {
    id: "3",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Non-Fiction",
    year: 1988,
    description:
      "An exploration of cosmology, black holes, and the nature of the universe.",
    rating: 4.6,
    image: "https://covers.openlibrary.org/b/id/240726-L.jpg",
  },
  {
    id: "4",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    year: 2011,
    description:
      "A journey through human evolution, from hunter-gatherers to modern societies.",
    rating: 4.7,
    image: "https://covers.openlibrary.org/b/id/8370226-L.jpg",
  },
  {
    id: "5",
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    year: 1965,
    description:
      "The epic saga of politics, religion, and ecology on the desert planet Arrakis.",
    rating: 4.4,
    image: "https://covers.openlibrary.org/b/id/8101356-L.jpg",
  },
  {
    id: "6",
    title: "1984",
    author: "George Orwell",
    category: "Sci-Fi",
    year: 1949,
    description:
      "A dystopian novel depicting a totalitarian regime under constant surveillance.",
    rating: 4.9,
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    id: "7",
    title: "Harry Potter and the Sorcerer’s Stone",
    author: "J.K. Rowling",
    category: "Fantasy",
    year: 1997,
    description:
      "The beginning of Harry Potter’s magical journey at Hogwarts School of Witchcraft and Wizardry.",
    rating: 4.8,
    image: "https://covers.openlibrary.org/b/id/7984916-L.jpg",
  },
  {
    id: "8",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    year: 1937,
    description:
      "Bilbo Baggins embarks on an unexpected journey with dwarves to reclaim treasure guarded by a dragon.",
    rating: 4.7,
    image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
  },
  {
    id: "9",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Romance",
    year: 1813,
    description:
      "A romantic novel about manners, upbringing, morality, and marriage.",
    rating: 4.6,
    image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
  },
  {
    id: "10",
    title: "Moby Dick",
    author: "Herman Melville",
    category: "Adventure",
    year: 1851,
    description:
      "Captain Ahab's obsessive quest for revenge against the white whale.",
    rating: 4.2,
    image: "https://covers.openlibrary.org/b/id/7222276-L.jpg",
  },
  {
    id: "11",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiction",
    year: 1951,
    description:
      "Holden Caulfield recounts his days in New York after being expelled from prep school.",
    rating: 4.0,
    image: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
  },
  {
    id: "12",
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Philosophy",
    year: 1988,
    description:
      "A shepherd named Santiago dreams of finding treasure in the Egyptian pyramids.",
    rating: 4.3,
    image: "https://covers.openlibrary.org/b/id/8776046-L.jpg",
  },
  {
    id: "13",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    year: 1954,
    description:
      "The epic quest to destroy the One Ring and defeat the Dark Lord Sauron.",
    rating: 4.9,
    image: "https://covers.openlibrary.org/b/id/8728196-L.jpg",
  },
  {
    id: "14",
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Sci-Fi",
    year: 1932,
    description:
      "A dystopian society driven by technological advancements and strict social control.",
    rating: 4.4,
    image: "https://covers.openlibrary.org/b/id/8772156-L.jpg",
  },
  {
    id: "15",
    title: "The Fault in Our Stars",
    author: "John Green",
    category: "Romance",
    year: 2012,
    description:
      "Two teenagers with cancer fall in love and confront their mortality.",
    rating: 4.5,
    image: "https://covers.openlibrary.org/b/id/7444346-L.jpg",
  },
  {
    id: "16",
    title: "Gone Girl",
    author: "Gillian Flynn",
    category: "Thriller",
    year: 2012,
    description:
      "A psychological thriller about a marriage gone terribly wrong.",
    rating: 4.1,
    image: "https://covers.openlibrary.org/b/id/7269846-L.jpg",
  },
  {
    id: "17",
    title: "The Shining",
    author: "Stephen King",
    category: "Horror",
    year: 1977,
    description:
      "A family is isolated in a haunted hotel, and madness begins to consume them.",
    rating: 4.6,
    image: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
  },
  {
    id: "18",
    title: "Dracula",
    author: "Bram Stoker",
    category: "Horror",
    year: 1897,
    description:
      "The iconic vampire Count Dracula's attempt to move from Transylvania to England.",
    rating: 4.4,
    image: "https://covers.openlibrary.org/b/id/8231561-L.jpg",
  },
  {
    id: "19",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    category: "Thriller",
    year: 2003,
    description:
      "A symbologist uncovers secrets hidden in famous works of art and the Catholic Church.",
    rating: 4.3,
    image: "https://covers.openlibrary.org/b/id/7352166-L.jpg",
  },
  {
    id: "20",
    title: "Angels and Demons",
    author: "Dan Brown",
    category: "Thriller",
    year: 2000,
    description:
      "A thrilling adventure involving the Illuminati and the Vatican.",
    rating: 4.2,
    image: "https://covers.openlibrary.org/b/id/7453126-L.jpg",
  },
  {
    id: "21",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    category: "Sci-Fi",
    year: 2008,
    description:
      "A dystopian society forces teenagers into televised battles for survival.",
    rating: 4.7,
    image: "https://covers.openlibrary.org/b/id/7353506-L.jpg",
  },
  {
    id: "22",
    title: "Catching Fire",
    author: "Suzanne Collins",
    category: "Sci-Fi",
    year: 2009,
    description:
      "The second installment in the Hunger Games trilogy, with rebellion brewing.",
    rating: 4.6,
    image: "https://covers.openlibrary.org/b/id/7353516-L.jpg",
  },
  {
    id: "23",
    title: "Mockingjay",
    author: "Suzanne Collins",
    category: "Sci-Fi",
    year: 2010,
    description:
      "Katniss Everdeen becomes the symbol of rebellion against the Capitol.",
    rating: 4.5,
    image: "https://covers.openlibrary.org/b/id/7353526-L.jpg",
  },
  {
    id: "24",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    category: "Mystery",
    year: 2005,
    description:
      "A journalist and a hacker investigate the disappearance of a wealthy heiress.",
    rating: 4.5,
    image: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
  },
  {
    id: "25",
    title: "Sherlock Holmes: The Complete Novels",
    author: "Arthur Conan Doyle",
    category: "Mystery",
    year: 1892,
    description:
      "The legendary detective Sherlock Holmes and his adventures.",
    rating: 4.9,
    image: "https://covers.openlibrary.org/b/id/8232001-L.jpg",
  },
  {
    id: "26",
    title: "Frankenstein",
    author: "Mary Shelley",
    category: "Horror",
    year: 1818,
    description:
      "Victor Frankenstein creates a monster that ultimately seeks revenge on its creator.",
    rating: 4.4,
    image: "https://covers.openlibrary.org/b/id/8232011-L.jpg",
  },
  {
    id: "27",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "Fiction",
    year: 2003,
    description:
      "A story of friendship, betrayal, and redemption set in Afghanistan.",
    rating: 4.8,
    image: "https://covers.openlibrary.org/b/id/8232021-L.jpg",
  },
  {
    id: "28",
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    category: "Fiction",
    year: 2007,
    description:
      "The story of two Afghan women brought together by war and fate.",
    rating: 4.7,
    image: "https://covers.openlibrary.org/b/id/8232031-L.jpg",
  },
];
